package com.f_lab.java_commerce.domain;

public enum OrderStatus {
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    DELIVERY_PENDING,
    DELIVERY_STARTED,
    DELIVERY_COMPLETED,
    CANCEL_REQUESTED,
    CANCEL_COMPLETED,
    RETURN_REQUESTED,
    RETURN_COMPLETED,
    EXCHANGE_REQUESTED,
    EXCHANGE_COMPLETED,
    PURCHASE_COMPLETED
}
